name: Build And Test

on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]
env:
    BuildPlatform: Release
    DOTNET_VERSION: '5.x'
jobs:
    build:
        runs-on: windows-latest
        steps:
        - uses: actions/checkout@v2
        - name: Setup .NET
          uses: actions/setup-dotnet@v1
          with:
            dotnet-version: 5.x
        - name: Restore dependencies
          run: dotnet restore
        - name: Build Web Project
          run: dotnet build ./YamlPlayground.Web/YamlPlayground.Web.csproj -property:Configuration=${{env.BuildPlatform}}
        - name: Unit Test
          run: dotnet test ./Yamlplayground.Tests/Yamlplayground.Tests.csproj --verbosity normal --filter TestCategory='Unit'